language: go
os:
  - linux

git:
  depth: 1

notifications:
  email: false

before_install:
  - go get github.com/fluent/fluent-bit-go/output
  - go get github.com/nokute78/msgpack-microscope/pkg/msgpack

script:
  - go vet ./...
  - go test -v -race ./...